baseURL = 'https://martinphysics.club/'
title = 'Martin‘s Physics Club'
copyright = '© 2020-2026 [martinphysics.club](/)'
theme = 'PaperMod'
defaultContentLanguage = 'en'
locale = 'en-US'
timeZone = 'Asia/Shanghai'
hasCJKLanguage = true
enableRobotsTXT = true

[params]
  env = 'production'
  description = 'Physics, programming, and exploration'
  defaultTheme = 'auto'
  disableThemeToggle = false
  comments = true
  ShowReadingTime = true
  ShowWordCount = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowRssButtonInSectionTermList = true
  ShowPageNums = true
  disableSpecial1stPost = true
  mainSections = ['post']
  DateFormat = '2006-01-02'

  [params.profileMode]
    enabled = false

  [params.homeInfoParams]
    Title = 'Martin‘s Physics Club'
    Content = 'Physics, programming, and exploration'

  [params.assets]
    favicon = 'favicon.svg'
    favicon16x16 = 'favicon.svg'
    favicon32x32 = 'favicon.svg'
    apple_touch_icon = 'favicon.svg'
    safari_pinned_tab = 'favicon.svg'

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Posts'
  url = '/posts/'
  weight = 2
[[menu.main]]
  name = 'Topics & Tags'
  url = '/topics/'
  weight = 3
[[menu.main]]
  name = 'LightDraw.Browser'
  url = 'https://lightdraw.martinphysics.club/'
  weight = 4
[[menu.main]]
  name = 'EdiTools'
  url = 'https://tools.edi.wang/'
  weight = 5
[[menu.main]]
  name = 'RSS'
  url = '/index.xml'
  weight = 6

[markup.highlight]
  noClasses = false
[markup.goldmark.renderer]
  unsafe = false
[pagination]
  pagerSize = 6
[caches.images]
  dir = ':cacheDir/images'
